### ISSUE TITLE
When I use Databinding-ktx as android-library, It will see an error on build.

### ISSUE THREAD

**Issue by kwmt** [wada811/DataBinding-ktx#11]
When I  use this library as android-library and  use the android-library in another android project,  you can see below an error message:

```
Could not find com.github.wada811:DataBinding-ktx:5.0.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/github/wada811/DataBinding-ktx/5.0.0/DataBinding-ktx-5.0.0.pom
  - https://jcenter.bintray.com/com/github/wada811/DataBinding-ktx/5.0.0/DataBinding-ktx-5.0.0.pom
  - file:/Users/kwmt/.m2/repository/com/github/wada811/DataBinding-ktx/5.0.0/DataBinding-ktx-5.0.0.pom
Required by:
    project :app > net.kwmt27.mylibrary:databinding-ktx:1.0
```

If it sets the following in app module, the error disappears, but I don't want to set it.

```
maven { url "https://www.jitpack.io" }
```

You can reproduce this repo.
https://github.com/kwmt/databinding-ktx

Do you have any idea?

**Comment by wada811** [comment]
If you don't use DataBinding-ktx in app module, you can exclude DataBinding-ktx in the following way.

```
implementation("net.kwmt27.mylibrary:databinding-ktx:1.0") {
   exclude group: 'com.github.wada811', module: 'DataBinding-ktx'
}
```

Is this OK?

**Comment by kwmt** [comment]
Thank you for your reply 😄 
It's OK. But, I don't want to burden them, who use an app module (ex: MyApplication) , as possible.

I just want to write the following, if possible.
```
implementation "net.kwmt27.mylibrary:databinding-ktx:1.0"
```

If it's difficult, I will close the issue.

**Comment by wada811** [comment]
I just learned that it's better to use `compileOnly`.
You can write the following in the android-library.

```
compileOnly 'com.github.wada811:DataBinding-ktx:5.0.0'
```

ref. [Dependency configurations \| Add build dependencies  \|  Android Developers](https://developer.android.com/studio/build/dependencies#dependency_configurations)

Please try it 👍

**Comment by kwmt** [comment]
@wada811 I'm sorry for the late reply.
I tried to use `compileOnly`.

If it doesn't use `DataBinding-ktx` in the android-library, [the build error](https://github.com/wada811/DataBinding-ktx/issues/11#issue-703661949) has disappeared.

But if it use `DataBinding-ktx` in the android-library,  I encountered another runtime error:

```
020-09-21 14:28:13.292 29628-29628/net.kwmt27.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.kwmt27.myapplication, PID: 29628
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/wada811/databinding/ActivityDataBinding;
        at net.kwmt27.mylibrary.MainLibActivity.<init>(MainLibActivity.kt:10)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1250)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wada811.databinding.ActivityDataBinding" on path: DexPathList[[zip file "/data/app/net.kwmt27.myapplication-DUJlkd9sygpO-uaC_cp0iw==/base.apk"],nativeLibraryDirectories=[/data/app/net.kwmt27.myapplication-DUJlkd9sygpO-uaC_cp0iw==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at net.kwmt27.mylibrary.MainLibActivity.<init>(MainLibActivity.kt:10) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1250) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

You will be able to reproduce [this commit](https://github.com/kwmt/databinding-ktx/commit/9d15c7821675c6c3a9c8ed9e15639cd514e04b4d).


Thanks!

**Comment by wada811** [comment]
@kwmt Sorry, I just understand that it's wrong to use `compileOnly` and you have no choice but to do add the following. 🙇‍♂️ 
```
maven { url "https://www.jitpack.io" }
```

**Comment by kwmt** [comment]
Oh, I see. 
Thank you very much 🙇
