### ISSUE TITLE
NoSuchMethodException 

### ISSUE THREAD

**Issue by tapanrgohil** [wada811/DataBinding-ktx#4]
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
     Caused by: java.lang.NoSuchMethodException:
```

when try to inflate in fragment getting error

**Comment by wada811** [comment]
Paste full stacktrace.
